# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/avin/Documents/embedded_lab4/embedded_lab4.srcs/sources_1/ip/picture_1/picture.xci
# IP: The module: 'picture' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/avin/Documents/embedded_lab4/embedded_lab4.srcs/sources_1/ip/picture_1/picture_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'picture'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/avin/Documents/embedded_lab4/embedded_lab4.srcs/sources_1/ip/picture_1/picture.xci
# IP: The module: 'picture' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/avin/Documents/embedded_lab4/embedded_lab4.srcs/sources_1/ip/picture_1/picture_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'picture'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
